"""Project-wide constants."""

DEFAULT_CONCRETE_ELASTIC_MODULUS_EXPRESSION = "4700 * sqrt(f_c_mpa)"
DEFAULT_STEEL_ELASTIC_MODULUS_MPA = 200000.0
DEFAULT_EXPECTED_STEEL_YIELD_STRENGTH_MPA = 470.0
DEFAULT_WORKSHOP_OUTPUT_SUBDIRECTORIES = ("figures", "tables", "reports", "data")

