sections:
  workshop_01_base_column:
    type: square_reinforced_concrete_column
    width:
      value: 75.0
      unit: cm
    height:
      value: 75.0
      unit: cm
    clear_cover_to_tie:
      value: 4.0
      unit: cm
    longitudinal_reinforcement:
      count: 16
      bar_mark: "#7"
    transverse_reinforcement:
      bar_mark: "#4"
      spacing:
        value: 10.0
        unit: cm

